Merge spark-operator develop
stackabletech/spark-operator pull request #7
Opened 2020-12-23 13:03 UTC by maltesander

- tested with agent  https://github.com/stackabletech/agent/pull/32/commits/d888e04f4ed63541dc76266e74098599e8eceb94

2020-12-23 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stackabletech/spark-operator?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stackabletech/spark-operator?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stackabletech/spark-operator?pullRequest=7) it.</sub>

2020-12-28 15:16 UTC, lfrancke commented on README.md
> +mvn exec:java -Dexec.mainClass=com.stackable.spark.operator.SparkOperatorMain
Indent (4 spaces) so it appears as a code block

2020-12-28 15:16 UTC, lfrancke commented on README.md
> +## usage
```suggestion
## Usage
```

2020-12-28 15:19 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +import java.util.Collections;
Unused

2020-12-28 15:21 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> + * Abstract crd Controller to work with customize crds. Applies given crd and orders events (add, update, delete)
```suggestion
 * Abstract CRD Controller to work with custom CRDs. Applies given CRD and orders events (add, update, delete)
```

2020-12-28 15:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> + * in an blocking queue. crdClass extending CustomResource and crdClassList extending CustomResourceList required!
`crdClass` and `crdClassList` not referenced anywhere else in this class.
Are you referring to the type parameters?
If so you already have @param attributes so this can be dropped.

2020-12-28 15:26 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +  private static final Logger LOGGER = Logger.getLogger(AbstractCrdController.class.getName());
This is probably recurring so I'll only comment on it once but I think it'd be good to use SLF4J instead of log4j 1.x

2020-12-28 15:28 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +      LOGGER.trace("No namespace found via config, assuming " + namespace);
Also only going to comment once: When you use SLF4J this can be changed to

```suggestion
      LOGGER.trace("No namespace found via config, assuming {}", namespace);
```

2020-12-28 15:30 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +        LOGGER.error(e.getMessage());
```suggestion
        LOGGER.error("Error loading YAML from {}", path, e);
```

2020-12-28 15:33 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    crdMetadata = loadYaml(crdPath);
This does not check the return value.
Should the load fail it'll return null which will lead to al NPE in `getCrdContext`

2020-12-28 15:42 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +      LOGGER.warn("multiple crds available ... using first one");
I know this is only used with hardcoded values for now and CRDs we ship ourselves but if you move this to a library later I'm in favor of erroring out in these kinds of cases.

Maybe instead of accepting a list have this just accept a single `CustomResourceDefinition` parameter so the caller has to decide how she wants to handle this.

2020-12-28 15:44 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    if (crd.getSpec().getVersions().size() > 1) {
On this one I'm not sure myself (especially before having read the whole code) but should this not look at all versions and use only the one that is set to `served: true`?

2020-12-28 15:48 UTC, lfrancke requested changes
Not done yet, submitting now so you have something to look at.
Only looked at 6 out of 58 files so far...

2020-12-28 21:47 UTC, lfrancke requested changes
Part 2. Again, not done yet.

The biggest thing I need to think about is that we model our operators in totally different ways. I'm not saying one is better than the other.

2020-12-28 21:47 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    while (!getCrdSharedIndexInformer().hasSynced() || !podInformer.hasSynced()) {}
Again, busy waiting, this needs to be changed to something different

2020-12-28 21:47 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkStateMachine.java
> +   * @param crd - crd class
Again, extra dashes in this file

2020-12-28 21:47 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkSystemdStateMachine.java
> +public class SparkSystemdStateMachine implements SparkStateMachine<SparkCluster, SystemdEvent> {
Okay, I'm just starting to get into this state machine business and I'm not sure yet how it all works but I'm almost certain that the operator shouldn't use `systemd` terminology.

Ideally the operator has no clue how it's handled in the background. The agent - at this moment - doesn't even use systemd for example.

I'm not sure what a better term would be yet...

2021-01-15 15:27 UTC, lfrancke requested changes

2021-01-15 15:27 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkClusterStateMachine.java
> +public class SparkClusterStateMachine implements SparkStateMachine<SparkCluster, ClusterEvent> {
I have to be honest. I don't think the StateMachine approach is very beneficial for us here.

I'd just rather have all the things from your `transition` method pulled out into separate methods (e.g. `checkForMissingWorkers`, `checkForMissingMasters`, ...) and the stuff in your `getEvent` method can call those. methods.

For an example see here: https://github.com/strimzi/strimzi-kafka-operator/blob/master/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java#L264-L376

You do a bit of that in the part where you delete excess pods.

2021-01-15 15:30 UTC, lfrancke commented
I have submitted my latest round of review comments.

I'm not sure if I like the StateMachine and running- & stagedCommands approach.
I know that the latter came out of a discussion with us and it was one of our suggestions but it seems (this is a gut feeling) fragile.

In terms of the implementation itself I do not really see a benefit for the state machine either.
Maybe it's just me but I find it hard to reason about what's going on with the Events and Transitions and so on.
You actually do check the current state against the spec which you use to _generate_ the Event which is later used to trigger the correct code for the event.
I don't quite understand why you not just call the correct method directly. I don't think we need the indirection.

I also don't have a better answer to the _commands_ question yet. We should discuss this again.

I'll stop reviewing for now as I'll wait for our discussions and some changes first because I assume that they might change the code quite a bit.

2021-01-17 10:15 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    while (!crdSharedIndexInformer.hasSynced()) {}
added sleep(100)

2021-01-17 10:19 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/crd/CrdClass.java
> + * @param <Spec>   - crd spec
done for all files

2021-01-17 10:20 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    while (!getCrdSharedIndexInformer().hasSynced() || !podInformer.hasSynced()) {}
added sleep(100)

2021-01-17 10:20 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkSystemdStateMachine.java
> +public class SparkSystemdStateMachine implements SparkStateMachine<SparkCluster, SystemdEvent> {
renamed to manager - still could use a better name

2021-01-17 10:21 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +        onCrdDelete(crd, deletedFinalStateUnknown);
i would like to keep it for the future. maybe we want to react on delete events

2021-01-17 10:22 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    while (true) {
only InterruptedException is caught. Not sure how to shut it down otherwise.

2021-01-17 10:26 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    writeCrd(namespace, crdMetadata);
added return value of writeCrd

2021-01-17 10:26 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +      (Class<CrdList>) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[1],
moved to a functions

2021-01-17 10:26 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    if (crd.getSpec().getVersions().size() > 1) {
done, now going for served version

2021-01-17 10:27 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +    crdMetadata = loadYaml(crdPath);
added check for return value

2021-01-17 10:28 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/abstractcontroller/AbstractCrdController.java
> +        builder.withVersion(crd.getSpec().getVersions().get(0).getName());
yeah that was definitly a bug ;) fixed and going for version from the loop

2021-01-17 10:29 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkNodeSelector.java
> +public class SparkNodeSelector implements KubernetesResource {
i added a nodeName field for hardcoded access.

2021-01-17 10:31 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkNode.java
> +public class SparkNode implements KubernetesResource {
SparkNode summarizes shared functionality for master, worker and historyserver. The enum is to differentiate as well as name the single nodes (pods).
Master, worker and history server eventually get different fields for configuration, so i want to work on the child classes and only keep shared information in the SparkNode.

2021-01-17 10:32 UTC, maltesander commented on pom.xml
> +        <version>1.6.0</version>
i needed to download it for the spark application launcher (required spark-submit and the library stuff). But since we do not use that anyways i removed all of that.

2021-01-17 10:34 UTC, maltesander commented on pom.xml
> +        <version>3.8.0</version>
done

2021-01-17 10:37 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkClusterStateMachine.java
> +public class SparkClusterStateMachine implements SparkStateMachine<SparkCluster, ClusterEvent> {
yeah i will drop the state machine and refactor to the "checkFor..." methods approach

2021-01-17 10:38 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkClusterStateMachine.java
> +public class SparkClusterStateMachine implements SparkStateMachine<SparkCluster, ClusterEvent> {
for me, with the waiting for nodenames, wait for the master to run before creating workers etc (or at least have a nodename for the master to start workers) i figured naturally it is a state machine.
But now i would favor the mentioned apporach. Should not be too much work to change that.

2021-01-17 10:49 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkManagerStateMachine.java
> +public class SparkManagerStateMachine implements SparkStateMachine<SparkCluster, ManagerEvent> {
No! ;)
Will be obsolete with dropping all the state machines .

2021-01-17 10:49 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkManagerStateMachine.java
> +      }
will be moved to the cluster controller without state machines

2021-01-17 10:50 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkManagerStateMachine.java
> +      && managerStatus.getRunningCommand().getStatus().equals(SparkManagerCommandState.STARTED.toString())) {
STARTED should be PENDING as discussed

2021-01-17 10:55 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +      List<Pod> pods = podLister.list();
createPodName? 
No because the method can take multiple node types (SparkNode... nodes) to e.g. get all pods (master, worker, history) related to the cluster

2021-01-17 10:57 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    String podName = cluster.getMetadata().getName() + "-" + node.getNodeType() + "-";
yeah that is ugly but works in current implementation. I add a TODO:

2021-01-17 10:58 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +      }
That is really bad for now. But when testing with the fabric8 mockserver, the lister didnt work at all -> didnt not return any pods. So for production this is not required. I added it to be able to work on tests. Not sure what a valid solution is here though. Need to do some more investigation for that.

2021-01-17 10:59 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +      }
Same as above. The lister doesnt work with the mock server.

2021-01-17 11:04 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkManagerStateMachine.java
> +      }
I should investigate that definitely. For now, it didnt give me any problems. I will add a TODO:  
For me Terminating pods wont be caught by getPodsByNode, so they are basically done. If there are no other pods for the specific cluster i would assume all are deleted/stopped etc. ?
But yeah if terminating does not work or has errors, i wont even know about that.

2021-01-17 11:06 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/statemachine/SparkManagerStateMachine.java
> +        }
We only have a staged command when a new manager crd is applied with a staged command like restart.

It will get removed when the command is started / pending.

2021-01-17 11:08 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +          && selector.getName().equals(pod.getMetadata().getLabels().get(SparkOperatorConfig.POD_SELECTOR_NAME.toString()))) {
It is possible by matching the pod status (which we need to write). I just wanted to have a working solution here for now. Its not good unfortunately. I hope i get to change that in future releases.

2021-01-17 11:09 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +        }
at the start of the getEvent (transition) function:
    // delete excess master pods
    // TODO: leader?
    if (SparkVersionedClusterControllerHelper.getPodSpecToClusterDifference(master, masterPods) < 0) {
      List<Pod> deletedPods = controller.deletePods(masterPods, crd, master);
      LOGGER.debug("[{}] - deleted {} {} pod(s): {}",
        state.name(), deletedPods.size(), master.getNodeType(), SparkVersionedClusterControllerHelper.metadataListToDebug(deletedPods));
    }
    // delete excess worker pods
    if (SparkVersionedClusterControllerHelper.getPodSpecToClusterDifference(worker, workerPods) < 0) {
      List<Pod> deletedPods = controller.deletePods(workerPods, crd, worker);
      LOGGER.debug("[{}] - deleted {} {} pod(s): {}",
        state.name(), deletedPods.size(), worker.getNodeType(), SparkVersionedClusterControllerHelper.metadataListToDebug(deletedPods));
    }

2021-01-17 11:15 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    String cmName = podName + "-cm";
Ok did not know that. TODO added.

2021-01-17 11:17 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    return pod.getMetadata().getName() + "-cm";
TODO added

2021-01-17 11:18 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkClusterSpec.java
> +  private List<Toleration> tolerations = new ArrayList<>();
Yes. They ill be added from the operator. Not provided via CRD anymore.

2021-01-17 11:20 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkClusterSpec.java
> +  private Boolean metrics;
No Idea. Fixed it to primitive type.

2021-01-17 11:23 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkClusterSpec.java
> +  private String secret;
Done

2021-01-17 11:25 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkClusterStatusImage.java
> +public class SparkClusterStatusImage implements KubernetesResource {
Its a pojo to read the status. When creating the cluster, name, timestamp and version are written. Required for e.g. cluster update.

2021-01-21 12:38 UTC, closed without merging